# Generated by Django 5.2 on 2025-04-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
