# Generated by Django 5.2 on 2025-04-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_quiz_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='multiple_answers',
        ),
    ]
