# Generated by Django 5.2 on 2025-04-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_question_multiple_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='editing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='editing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='editing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='due date'),
        ),
    ]
